### PR TITLE
Negative numbers for BInt 

### PR DESCRIPTION
**Pull request by synlestidae**
See #1 

I don't expect you'll accept this pull request straight away. Feedback would be appreciated!

### CODE REVIEW

**Comment by MatejLach** [comment]
Hey @synlestidae, amazing work,
You're correct, I somehow completely overlooked the possibility of negative integers 😳 nice find.
I see you also formatted the code and written some good tests as well, which was very much needed.

The code looks good to me - although,  could you please add `#[cfg(test)]` for `decode_str_to_i64`, (maybe `decode_bytes_to_i64` would be a better name for the function?), and `test_decode_str` helper functions as well as putting `#[allow(unused_imports)]` to the top of `mod.rs`?
Also, `#![feature(inclusive_range_syntax)]` can be completely removed from `lib.rs` now that it's not needed.

Thanks a lot for the _great_ work, I really appreciate it! 👍

**Comment by synlestidae** [comment]
No worries, rustfmt takes care of the formatting! I've added the other changes you asked for now.

**Comment by MatejLach** [comment]
Yeah, I should use `rustfmt` myself.
Before I merge, could you perhaps squash the last 4 or so commits together into one, since they're all related to testing? 

Thanks @synlestidae

**Comment by synlestidae** [comment]
Okay done, think it's good now

**Comment by MatejLach** [comment]
👍

**Pull request merged**
